### ISSUE TITLE
Documentation for the plugin

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-training#1]
Write up some instructions of how to use this plugin and place then here on the Wiki
https://github.com/DiscipleTools/disciple-tools-training/wiki
and/or in the https://disciple-tools.readthedocs.io/en/latest/index.html

**Comment by ChrisChasm** [comment]
Great challenge. And I'll be taking it up in the next few weeks. I'm moving this to the discussions area and I'll make notes there for additions on documentation. 

https://github.com/DiscipleTools/disciple-tools-training/discussions/13
