### ISSUE TITLE
Improve the mobile view

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-training#10]
The list of trainings in mobile view is not great because it shows information but not the field definitions.

![Screen Shot 2020-08-10 at 10 59 25 pm](https://user-images.githubusercontent.com/43966676/89855938-77687f80-db5d-11ea-9bae-64c665c7ce81.png)

![Screen Shot 2020-08-10 at 11 01 59 pm](https://user-images.githubusercontent.com/43966676/89855957-851e0500-db5d-11ea-972d-cccc03f4fdf4.png)

**Comment by ChrisChasm** [comment]
This has been improved. We've used more condensed stacking and labeling.
