### ISSUE TITLE
Add Members Broken

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-training#15]
As reported by Josephine (https://disciple-tools.slack.com/archives/CDXNVC892/p1615795734047000) 

The Members typeahead doesn't load. That appears to be first because the https://github.com/DiscipleTools/disciple-tools-training/blob/d9d16d2d4ba67072bec7170e4c3fdb6b4aad0998/post-type/module-base.php#L472 the custom_display is set to true which means it doesn't get displayed by the by the render_field_for_display function. 

But just setting the custom_display to false doesn't resolve the issue totally either. The field displays, but there is a JS error that occurs because the field doesn't exist in the Javascript properly.

**Comment by corsacca** [comment]
Thanks @micahmills for fixing this one.
