### ISSUE TITLE
Reorder sidebar menu items - Favorite & Recently Viewed

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-training#20]
Within DT the menu items like "Favorite Contacts" and "My Recently Viewed" are towards the top of the menu list and not at the bottom (last places). Moving them to be consistent with the other areas of DT (like contacts and groups) will help the user.

![Screen Shot 2022-01-08 at 04 47 09](https://user-images.githubusercontent.com/43966676/148642642-fc09a6be-1905-4a8e-8255-7c6a11622a00.png)

**Comment by corsacca** [comment]
Thanks @mikeallbutt 
Should now be in order with v2.6.6
<img width="289" alt="image" src="https://github.com/DiscipleTools/disciple-tools-training/assets/24901539/e3cc4caf-51e6-42c4-a1e2-03fe704cfd25">
