### ISSUE TITLE
Dates not saving on Safari

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-training#34]
Using the meeting times date selector with the Trainings plugin installed, dates aren't being saved when using Safari on Mac. The payload to the API request is `{"meeting_times":[{"value":null}]}` instead of containing the selected date.

**Comment by corsacca** [comment]
If the issue is with moment, lets move to migrating away from using moment.

**Comment by corsacca** [comment]
Thanks @kodinkat 
Activity only shows the date, todo for sometime is upgrading it to show date and time.
Time is shown on the date series itself, so there is good.
