### ISSUE TITLE
Translation ready

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-training#4]
The plugin works in English but needs to work in other languages the DT is offered in also.

**Comment by mikeallbutt** [comment]
Here are some screenshots that show where the text remains in English when it should be being translated. The text has been set correctly in the /wp-admin/admin.php?page=dt_options&tab=custom-fields but the plugin is not using the data.

![Screenshot 2020-07-12 07 45 51](https://user-images.githubusercontent.com/43966676/87246833-59e8ae80-c415-11ea-965a-e58ddcdeb25b.png)
![Screenshot 2020-07-12 07 46 02](https://user-images.githubusercontent.com/43966676/87246834-5a814500-c415-11ea-83c9-47bc4dd4ee5b.png)
![Screenshot 2020-07-12 07 48 56](https://user-images.githubusercontent.com/43966676/87246835-5b19db80-c415-11ea-8c40-101af68611d6.png)
![Screenshot 2020-07-12 07 52 28](https://user-images.githubusercontent.com/43966676/87246836-5bb27200-c415-11ea-98ca-7377a5421d7e.png)

**Comment by ChrisChasm** [comment]
You are correct. We are turning our efforts towards getting the top plugins translated. I think this will get there first quarter of 2021.

**Comment by ChrisChasm** [comment]
Fixed and will be in the next release
